// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaebvlwwprhlvyglvwyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZWJ2bHd3cHJobHZ5Z2x2d3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1ODI2NTAsImV4cCI6MjA5NjE1ODY1MH0.jP0w4sYxKG7fOQk3sZdFXD2_y7Dr1s_XfOr3SVg9CXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});